# Generated by Django 3.2.18 on 2023-03-02 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Author name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Author photo')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='The slug is filled in automatically')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Binding')),
            ],
            options={
                'verbose_name': 'binding',
                'verbose_name_plural': 'Bindings',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book name')),
                ('cover_image', models.ImageField(upload_to='book_covers/', verbose_name='Cover photo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('slug', models.SlugField(max_length=255, verbose_name='The slug is filled in automatically')),
                ('year_of_first_publication', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of first publication')),
                ('year_of_publication', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of publication')),
                ('amount_pages', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Amount pages')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Weight')),
                ('edition', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edition')),
                ('literature_of_the_countries_of_the_world', models.CharField(blank=True, max_length=255, null=True, verbose_name='Literature of the countries of the world')),
                ('format', models.CharField(blank=True, max_length=255, null=True, verbose_name='Format')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISBN')),
                ('author', models.ManyToManyField(blank=True, related_name='books', to='books.Author', verbose_name='Author')),
                ('binding', models.ManyToManyField(blank=True, to='books.Binding', verbose_name='Binding')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Font')),
            ],
            options={
                'verbose_name': 'Font',
                'verbose_name_plural': 'Fonts',
            },
        ),
        migrations.CreateModel(
            name='Illustrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Illustrations')),
            ],
            options={
                'verbose_name': 'illustrations',
                'verbose_name_plural': 'Illustrations',
            },
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Illustrator name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='The slug is filled in automatically')),
            ],
            options={
                'verbose_name': 'illustrator',
                'verbose_name_plural': 'Illustrators',
            },
        ),
        migrations.CreateModel(
            name='Interpreter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Interpreter name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='The slug is filled in automatically')),
            ],
            options={
                'verbose_name': 'interpreter',
                'verbose_name_plural': 'Interpreters',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Paper')),
            ],
            options={
                'verbose_name': 'paper',
                'verbose_name_plural': 'Paper',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Publisher name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publishers/', verbose_name='Publisher photo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='The slug is filled in automatically')),
            ],
            options={
                'verbose_name': 'publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book series')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='The slug is filled in automatically')),
            ],
            options={
                'verbose_name': 'book series',
                'verbose_name_plural': 'Book series',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Terribly'), (2, 'Badly'), (3, 'Normally'), (4, 'Fine'), (5, 'Perfectly')], verbose_name='Rating')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Book review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of the review')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='The slug is filled in automatically')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='books.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='font',
            field=models.ManyToManyField(blank=True, to='books.Font', verbose_name='Font'),
        ),
        migrations.AddField(
            model_name='book',
            name='illustrations',
            field=models.ManyToManyField(blank=True, to='books.Illustrations', verbose_name='Illustrations'),
        ),
        migrations.AddField(
            model_name='book',
            name='illustrator',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.Illustrator', verbose_name='Illustrator'),
        ),
        migrations.AddField(
            model_name='book',
            name='interpreter',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.Interpreter', verbose_name='Interpreter'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(blank=True, to='books.Language', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='paper',
            field=models.ManyToManyField(blank=True, to='books.Paper', verbose_name='Paper'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.Publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.Series', verbose_name='Series'),
        ),
    ]
