# Generated by Django 3.2.18 on 2023-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Message subject')),
                ('massage', models.CharField(max_length=550, verbose_name='Message content')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active mailing')),
            ],
            options={
                'verbose_name': 'mailing list',
                'verbose_name_plural': 'Mailing list',
            },
        ),
    ]
